logging:
  level:
    org:
      springframework:
        cloud: DEBUG

spring:
  cloud:
    stream:
      bindings:
        userIn:
          destination: users.profile
          binder: nats1
        userOut:
          destination: users.profile
          binder: nats1
        accountIn:
          destination: account.register
          binder: nats2
        accountOut:
          destination: account.register
          binder: nats2
      binders:
        nats1:
          type: nats
          environment:
            nats:
              spring:
                cloud:
                  stream:
                    binder:
                      server: nats://localhost:4222
        nats2:
          type: nats
          environment:
            nats:
              spring:
                cloud:
                  stream:
                    binder:
                      server: nats://localhost:4222
